sonar.projectKey=cesizen
sonar.projectName=CESIZen
sonar.projectVersion=1.1.0

# Sources : web (Next.js) + mobile (React Native)
sonar.sources=CESIZen-Web/app,CESIZen-Web/controllers,CESIZen-Web/models,CESIZen-Web/lib,CESIZen-Web/components,CESIZen-Mobile/app,CESIZen-Mobile/controllers,CESIZen-Mobile/models,CESIZen-Mobile/lib,CESIZen-Mobile/components,CESIZen-Mobile/constants

sonar.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx

sonar.exclusions=**/node_modules/**,\
**/.next/**,\
**/public/sw.js,\
**/public/workbox-*.js,\
**/coverage/**,\
**/ios/**,\
**/android/**,\
**/.expo/**,\
**/dist/**,\
**/build/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

# Tests (mobile)
sonar.tests=CESIZen-Mobile/__tests__,CESIZen-Mobile/__mocks__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx,**/*.spec.ts,**/*.spec.tsx