sonar.projectKey=cesizen
sonar.projectName=CESIZen
sonar.projectVersion=1.0

sonar.sources=CESIZen-Web,CESIZen-Mobile
sonar.exclusions=**/node_modules/**,**/.next/**,**/.expo/**,**/coverage/**

sonar.host.url=http://localhost:9000