sonar.projectKey=CESIZen
sonar.projectName=CESIZen
sonar.projectVersion=1.1.0
sonar.sources=app,controllers,models,lib,components
sonar.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/sw.js,**/public/workbox-*.js
sonar.sourceEncoding=UTF-8
