sonar.projectKey=cesizen-web
sonar.organization=cesizen

sonar.sources=app,components,controllers,models,lib,src
sonar.tests=tests
sonar.exclusions=node_modules/**,.next/**,public/**

sonar.sourceEncoding=UTF-8
