sonar.projectKey=cesizen-mobile
sonar.organization=cesizen

sonar.sources=app,components,controllers,models,lib,constants
sonar.tests=__tests__
sonar.exclusions=node_modules/**,.expo/**,supabase/functions/**

sonar.sourceEncoding=UTF-8
